FROM zoeyvid/npmplus:latest

# Копируем мультиплексор
COPY multiplexor/bin/shoes /app/multiplexor/shoes
COPY multiplexor/config/config.yaml /app/multiplexor/config.yaml

# GUI компоненты
COPY multiplexor/ui /app/frontend/mplex-ui

# Делаем исполняемым
RUN chmod +x /app/multiplexor/shoes

# Запуск обоих
COPY start-all.sh /app/start-all.sh
RUN chmod +x /app/start-all.sh

ENTRYPOINT ["/app/start-all.sh"]
