listen: ":443"
rules:
  - match: "tls"
    # Forward HTTPS traffic to NPMplus (default HTTPS_PORT 8443)
    forward: "127.0.0.1:8443"
  - match: "ssh"
    forward: "127.0.0.1:22"
  - match: "vless"
    forward: "127.0.0.1:10585"
