- address: "0.0.0.0:1234"
  transport: tcp
  protocol:
    type: http
    rules:
      - name: "VLESS Protocol"
        lpn: ["vless"]
        target: 127.0.0.1:18443
      - name: "Nginx Domain"
        sni: ["extc.xgatex.ru"]
        target: npmplus:82
      - name: "Default SSL"
        target: 127.0.0.1:8443

