name: Build Caddy Image
on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/caddy.yml
      - global/caddy/Dockerfile
      - global/caddy/Caddyfile
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: zoeyvid
          password: ${{ github.token }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: global/caddy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zoeyvid/npmplus:caddy
            ghcr.io/zoeyvid/npmplus:caddy
            zoeyvid/npmplus:caddy-${{ github.run_number }}
            ghcr.io/zoeyvid/npmplus:caddy-${{ github.run_number }}
            zoeyvid/nginx-proxy-manager:caddy
            ghcr.io/zoeyvid/nginx-proxy-manager:caddy
