name: Build latest Docker Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'name of the release'
        required: true
        type: string
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: xenon007
          password: ${{ github.token }}
      - name: version
        run: |
          version="${{ inputs.tag }}-$(git rev-parse --short HEAD)-$(cat .version)"
          sed -i "s|\"2.12.3\"|\"$version\"|g" frontend/js/i18n/en-lang.json
          sed -i "s|\"2.12.3\"|\"$version\"|g" frontend/js/i18n/de-lang.json
          sed -i "s|\"2.12.3\"|\"$version\"|g" frontend/js/i18n/it-lang.json
          sed -i "s|\"2.12.3\"|\"$version\"|g" frontend/js/i18n/zh-lang.json
          sed -i "s|\"2.12.3\"|\"$version\"|g" frontend/package.json
          sed -i "s|\"2.12.3\"|\"$version\"|g" backend/package.json
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            xenon007/npmplus:latest
            ghcr.io/xenon007/npmplus:latest
            xenon007/npmplus:${{ inputs.tag }}
            ghcr.io/xenon007/npmplus:${{ inputs.tag }}
            xenon007/npmplus:${{ github.run_number }}
            ghcr.io/xenon007/npmplus:${{ github.run_number }}
            xenon007/nginx-proxy-manager:latest
            ghcr.io/xenon007/nginx-proxy-manager:latest
      - name: Show Nginx version
        run: |
          docker run --rm --init --entrypoint nginx xenon007/npmplus:latest -V
